package net.httpclient.wrapper.enums;

import lombok.Getter;
import org.jetbrains.annotations.NotNull;

/**
 * This enum follow the ISO 639-1 standard.
 * You can find the list of all the languages here:
 * <a href="https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes">Wikipedia</a>
 * <a href="http://www.lingoes.net/en/translator/langcode.htm">Lingoes</a>
 */
public enum AcceptLanguage {

    AF("af", "Afrikaans"),
    AF_ZA("af-ZA", "Afrikaans (South Africa)"),
    AR("ar", "Arabic"),
    AR_AE("ar-AE", "Arabic (U.A.E.)"),
    AR_BH("ar-BH", "Arabic (Bahrain)"),
    AR_DZ("ar-DZ", "Arabic (Algeria)"),
    AR_EG("ar-EG", "Arabic (Egypt)"),
    AR_IQ("ar-IQ", "Arabic (Iraq)"),
    AR_JO("ar-JO", "Arabic (Jordan)"),
    AR_KW("ar-KW", "Arabic (Kuwait)"),
    AR_LB("ar-LB", "Arabic (Lebanon)"),
    AR_LY("ar-LY", "Arabic (Libya)"),
    AR_MA("ar-MA", "Arabic (Morocco)"),
    AR_OM("ar-OM", "Arabic (Oman)"),
    AR_QA("ar-QA", "Arabic (Qatar)"),
    AR_SA("ar-SA", "Arabic (Saudi Arabia)"),
    AR_SY("ar-SY", "Arabic (Syria)"),
    AR_TN("ar-TN", "Arabic (Tunisia)"),
    AR_YE("ar-YE", "Arabic (Yemen)"),
    AZ("az", "Azeri (Latin)"),
    AZ_AZ_LATIN("az-AZ", "Azeri (Latin) (Azerbaijan)"),
    AZ_AZ_CYRILLIC("az-AZ", "Azeri (Cyrillic) (Azerbaijan)"),
    BE("be", "Belarusian"),
    BE_BY("be-BY", "Belarusian (Belarus)"),
    BG("bg", "Bulgarian"),
    BG_BG("bg-BG", "Bulgarian (Bulgaria)"),
    BS_BA("bs-BA", "Bosnian (Bosnia and Herzegovina)"),
    CA("ca", "Catalan"),
    CA_ES("ca-ES", "Catalan (Spain)"),
    CS("cs", "Czech"),
    CS_CZ("cs-CZ", "Czech (Czech Republic)"),
    CY("cy", "Welsh"),
    CY_GB("cy-GB", "Welsh (United Kingdom)"),
    DA("da", "Danish"),
    DA_DK("da-DK", "Danish (Denmark)"),
    DE("de", "German"),
    DE_AT("de-AT", "German (Austria)"),
    DE_CH("de-CH", "German (Switzerland)"),
    DE_DE("de-DE", "German (Germany)"),
    DE_LI("de-LI", "German (Liechtenstein)"),
    DE_LU("de-LU", "German (Luxembourg)"),
    DV("dv", "Divehi"),
    DV_MV("dv-MV", "Divehi (Maldives)"),
    EL("el", "Greek"),
    EL_GR("el-GR", "Greek (Greece)"),
    EN("en", "English"),
    EN_AU("en-AU", "English (Australia)"),
    EN_BZ("en-BZ", "English (Belize)"),
    EN_CA("en-CA", "English (Canada)"),
    EN_CB("English (Caribbean)", "en-CB"),
    EN_GB("English (United Kingdom)", "en-GB"),
    EN_IE("English (Ireland)", "en-IE"),
    EN_JM("English (Jamaica)", "en-JM"),
    EN_NZ("English (New Zealand)", "en-NZ"),
    EN_PH("English (Republic of the Philippines)", "en-PH"),
    EN_TT("English (Trinidad and Tobago)", "en-TT"),
    EN_US("English (United States)", "en-US"),
    EN_ZA("English (South Africa)", "en-ZA"),
    EN_ZW("English (Zimbabwe)", "en-ZW"),
    EO("Esperanto", "eo"),
    ES("Spanish", "es"),
    ES_AR("Spanish (Argentina)", "es-AR"),
    ES_BO("Spanish (Bolivia)", "es-BO"),
    ES_CL("Spanish (Chile)", "es-CL"),
    ES_CO("Spanish (Colombia)", "es-CO"),
    ES_CR("Spanish (Costa Rica)", "es-CR"),
    ES_DO("Spanish (Dominican Republic)", "es-DO"),
    ES_EC("Spanish (Ecuador)", "es-EC"),
    ES_ES_CT("Spanish (Castilian)", "es-ES"),
    ES_ES("Spanish (Spain)", "es-ES"),
    ES_GT("Spanish (Guatemala)", "es-GT"),
    ES_HN("Spanish (Honduras)", "es-HN"),
    ES_MX("Spanish (Mexico)", "es-MX"),
    ES_NI("Spanish (Nicaragua)", "es-NI"),
    ES_PA("Spanish (Panama)", "es-PA"),
    ES_PE("Spanish (Peru)", "es-PE"),
    ES_PR("Spanish (Puerto Rico)", "es-PR"),
    ES_PY("Spanish (Paraguay)", "es-PY"),
    ES_SV("Spanish (El Salvador)", "es-SV"),
    ES_UY("Spanish (Uruguay)", "es-UY"),
    ES_VE("Spanish (Venezuela)", "es-VE"),
    ET("Estonian", "et"),
    ET_EE("Estonian (Estonia)", "et-EE"),
    EU("Basque", "eu"),
    EU_ES("Basque (Spain)", "eu-ES"),
    FA("Farsi", "fa"),
    FA_IR("Farsi (Iran)", "fa-IR"),
    FI("Finnish", "fi"),
    FI_FI("Finnish (Finland)", "fi-FI"),
    FO("Faroese", "fo"),
    FO_FO("Faroese (Faroe Islands)", "fo-FO"),
    FR("French", "fr"),
    FR_BE("French (Belgium)", "fr-BE"),
    FR_CA("French (Canada)", "fr-CA"),
    FR_CH("French (Switzerland)", "fr-CH"),
    FR_FR("French (France)", "fr-FR"),
    FR_LU("French (Luxembourg)", "fr-LU"),
    FR_MC("French (Principality of Monaco)", "fr-MC"),
    GL("Galician", "gl"),
    GL_ES("Galician (Spain)", "gl-ES"),
    GU("Gujarati", "gu"),
    GU_IN("Gujarati (India)", "gu-IN"),
    HE("Hebrew", "he"),
    HE_IL("Hebrew (Israel)", "he-IL"),
    HI("Hindi", "hi"),
    HI_IN("Hindi (India)", "hi-IN"),
    HR("Croatian", "hr"),
    HR_BA("Croatian (Bosnia and Herzegovina)", "hr-BA"),
    HR_HR("Croatian (Croatia)", "hr-HR"),
    HU("Hungarian", "hu"),
    HU_HU("Hungarian (Hungary)", "hu-HU"),
    HY("Armenian", "hy"),
    HY_AM("Armenian (Armenia)", "hy-AM"),
    ID("Indonesian", "id"),
    ID_ID("Indonesian (Indonesia)", "id-ID"),
    IS("Icelandic", "is"),
    IS_IS("Icelandic (Iceland)", "is-IS"),
    IT("Italian", "it"),
    IT_CH("Italian (Switzerland)", "it-CH"),
    IT_IT("Italian (Italy)", "it-IT"),
    JA("Japanese", "ja"),
    JA_JP("Japanese (Japan)", "ja-JP"),
    KA("Georgian", "ka"),
    KA_GE("Georgian (Georgia)", "ka-GE"),
    KK("Kazakh", "kk"),
    KK_KZ("Kazakh (Kazakhstan)", "kk-KZ"),
    KN("Kannada", "kn"),
    KN_IN("Kannada (India)", "kn-IN"),
    KO("Korean", "ko"),
    KO_KR("Korean (Korea)", "ko-KR"),
    KOK("Konkani", "kok"),
    KOK_IN("Konkani (India)", "kok-IN"),
    KY("Kyrgyz", "ky"),
    KY_KG("Kyrgyz (Kyrgyzstan)", "ky-KG"),
    LT("Lithuanian", "lt"),
    LT_LT("Lithuanian (Lithuania)", "lt-LT"),
    LV("Latvian", "lv"),
    LV_LV("Latvian (Latvia)", "lv-LV"),
    MI("Maori", "mi"),
    MI_NZ("Maori (New Zealand)", "mi-NZ"),
    MK("FYRO Macedonian", "mk"),
    MK_MK("FYRO Macedonian (Former Yugoslav Republic of Macedonia)", "mk-MK"),
    MN("Mongolian", "mn"),
    MN_MN("Mongolian (Mongolia)", "mn-MN"),
    MR("Marathi", "mr"),
    MR_IN("Marathi (India)", "mr-IN"),
    MS("Malay", "ms"),
    MS_BN("Malay (Brunei Darussalam)", "ms-BN"),
    MS_MY("Malay (Malaysia)", "ms-MY"),
    MT("Maltese", "mt"),
    MT_MT("Maltese (Malta)", "mt-MT"),
    NB("Norwegian (Bokm?l)", "nb"),
    NB_NO("Norwegian (Bokm?l) (Norway)", "nb-NO"),
    NL("Dutch", "nl"),
    NL_BE("Dutch (Belgium)", "nl-BE"),
    NL_NL("Dutch (Netherlands)", "nl-NL"),
    NN_NO("Norwegian (Nynorsk) (Norway)", "nn-NO"),
    NS("ns", "Northern Sotho"),
    NS_ZA("ns-ZA", "Northern Sotho (South Africa)"),
    PA("pa", "Punjabi"),
    PA_IN("pa-IN", "Punjabi (India)"),
    PL("pl", "Polish"),
    PL_PL("pl-PL", "Polish (Poland)"),
    PS("ps", "Pashto"),
    PS_AR("ps-AR", "Pashto (Afghanistan)"),
    PT("pt", "Portuguese"),
    PT_BR("pt-BR", "Portuguese (Brazil)"),
    PT_PT("pt-PT", "Portuguese (Portugal)"),
    QU("qu", "Quechua"),
    QU_BO("qu-BO", "Quechua (Bolivia)"),
    QU_EC("qu-EC", "Quechua (Ecuador)"),
    QU_PE("qu-PE", "Quechua (Peru)"),
    RO("ro", "Romanian"),
    RO_RO("ro-RO", "Romanian (Romania)"),
    RU("ru", "Russian"),
    RU_RU("ru-RU", "Russian (Russia)"),
    SA("sa", "Sanskrit"),
    SA_IN("sa-IN", "Sanskrit (India)"),
    SE("se", "Sami (Northern)"),
    SE_FI("se-FI", "Sami (Northern) (Finland)"),
    SE_FI_SKOLT("se-FI-Skolt", "Sami (Skolt) (Finland)"),
    SE_FI_INARI("se-FI-Inari", "Sami (Inari) (Finland)"),
    SE_NO("se-NO", "Sami (Northern) (Norway)"),
    SE_NO_LULE("se-NO-Lule", "Sami (Lule) (Norway)"),
    SE_NO_SOUTHERN("se-NO-Southern", "Sami (Southern) (Norway)"),
    SE_SE("se-SE", "Sami (Northern) (Sweden)"),
    SE_SE_LULE("se-SE-Lule", "Sami (Lule) (Sweden)"),
    SE_SE_SOUTHERN("se-SE-Southern", "Sami (Southern) (Sweden)"),
    SK("sk", "Slovak"),
    SK_SK("sk-SK", "Slovak (Slovakia)"),
    SL("sl", "Slovenian"),
    SL_SI("sl-SI", "Slovenian (Slovenia)"),
    SQ("sq", "Albanian"),
    SQ_AL("sq-AL", "Albanian (Albania)"),
    SR_BA_LATIN("sr-BA-Latin", "Serbian (Latin) (Bosnia and Herzegovina)"),
    SR_BA_CYRILLIC("sr-BA-Cyrillic", "Serbian (Cyrillic) (Bosnia and Herzegovina)"),
    SR_SP_LATIN("sr-SP-Latin", "Serbian (Latin) (Serbia and Montenegro)"),
    SR_SP_CYRILLIC("sr-SP-Cyrillic", "Serbian (Cyrillic) (Serbia and Montenegro)"),
    SV("sv", "Swedish"),
    SV_FI("sv-FI", "Swedish (Finland)"),
    SV_SE("sv-SE", "Swedish (Sweden)"),
    SW("sw", "Swahili"),
    SW_KE("sw-KE", "Swahili (Kenya)"),
    SYR("syr", "Syriac"),
    SYR_SY("syr-SY", "Syriac (Syria)"),
    TA("ta", "Tamil"),
    TA_IN("ta-IN", "Tamil (India)"),
    TE("te", "Telugu"),
    TE_IN("te-IN", "Telugu (India)"),
    TH("th", "Thai"),
    TH_TH("th-TH", "Thai (Thailand)"),
    TL("tl", "Tagalog"),
    TL_PH("tl-PH", "Tagalog (Philippines)"),
    TN("tn", "Tswana"),
    TN_ZA("tn-ZA", "Tswana (South Africa)"),
    TR("tr", "Turkish"),
    TR_TR("tr-TR", "Turkish (Turkey)"),
    TT("tt", "Tatar"),
    TT_RU("tt-RU", "Tatar (Russia)"),
    TS("ts", "Tsonga"),
    UK("uk", "Ukrainian"),
    UK_UA("uk-UA", "Ukrainian (Ukraine)"),
    UR("ur", "Urdu"),
    UR_PK("ur-PK", "Urdu (Islamic Republic of Pakistan)"),
    UZ_LATIN("uz", "Uzbek (Latin)"),
    UZ_LATIN_UZ("uz-UZ", "Uzbek (Latin) (Uzbekistan)"),
    UZ_CYRILLIC_UZ("uz-UZ", "Uzbek (Cyrillic) (Uzbekistan)"),
    VI("vi", "Vietnamese"),
    VI_VN("vi-VN", "Vietnamese (Viet Nam)"),
    XH("xh", "Xhosa"),
    XH_ZA("xh-ZA", "Xhosa (South Africa)"),
    ZH("zh", "Chinese"),
    ZH_CN("zh-CN", "Chinese (S)"),
    ZH_HK("zh-HK", "Chinese (Hong Kong)"),
    ZH_MO("zh-MO", "Chinese (Macau)"),
    ZH_SG("zh-SG", "Chinese (Singapore)"),
    ZH_TW("zh-TW", "Chinese (T)"),
    ZU("zu", "Zulu"),
    ZU_ZA("zu-ZA", "Zulu (South Africa)");

    @NotNull @Getter
    private final String code;

    @NotNull @Getter
    private final String country;

    AcceptLanguage(@NotNull final String code,
                   @NotNull final String country) {
        this.code = code;
        this.country = country;
    }

    @Override
    public @NotNull String toString() {
        return (code + " [" + country + "]");
    }

}

